### ISSUE TITLE
Multiple sql supports

### ISSUE THREAD

**Issue by huangxinV587** [sql-machine-learning/pysqlflow#48]

**Comment by huangxinV587** [comment]
add support several sql statement split by ";"  for sqlflow(shell) and %%sqlflow(jupyter)

e.g. mysql
![image](https://user-images.githubusercontent.com/10525506/53848321-d0d69180-3fee-11e9-8b53-fbf5870e853f.png)


the multiple sql support is add for client.py. 
As the magic reuse the client, %%sqflow also get the multiple sql support

**Comment by huangxinV587** [comment]
https://github.com/wangkuiyi/pysqlflow/pull/46

**Comment by ktong** [comment]
The cli already supports pass multiple sqls using **nargs='+'** (https://github.com/wangkuiyi/pysqlflow/blob/develop/sqlflow/__main__.py#L6). The only change need is modify \_\_main__.py to call client.execute for each sql passed from cli.

Use sqlparse on client side may not be good option as it may not support customized sql or some database special sql. If multiple sql is must feature, I would like to implement multiple sqls support on server side and client pass anything from cli or cell to server and server runs sqls sequentially.

**Comment by tonyyang-svail** [comment]
This issue has been fixed by https://github.com/sql-machine-learning/pysqlflow/pull/83.
