### ISSUE TITLE
Rename pip package name from sqlflow into pysqlflow

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/pysqlflow#56]

**Comment by ktong** [comment]
Change name at https://github.com/sql-machine-learning/pysqlflow/blob/develop/setup.py#L10

**Comment by ktong** [comment]
Also need change in doc

**Comment by wangkuiyi** [comment]
It seems that we also need to rename the /sqlflow subdirectory into /pysqlflow.

**Comment by tonyyang-svail** [comment]
Too bad that the pypi package `pysqlflow` already exists.  https://pypi.org/project/pysqlflow/
