### ISSUE TITLE
Support variable replacing in SQL

### ISSUE THREAD

**Issue by Yancey1989** [sql-machine-learning/pysqlflow#74]
For the most scheduling scenarios, SQLFlow  should read from the current partition table, the scheduler can expose the partition name in to the env, such as `export DT=20190722`, SQLFlow SQL can be like:
``` sql
SELECT * from train 
WHERE partition = ${DT}
...
```

**Comment by typhoonzero** [comment]
Maybe more cases should be supported to suit the training cases, like:

- `${yyyyMMdd}`
- `${yyyyMMdd - 10d}`

**Comment by Yancey1989** [comment]
@typhoonzero will support the environment expand and **BIZDATE** format:
1.  SQL with `${x}` would be replaced by the OS environment variable `x`
2.  The general date format `${yyyymmdd}` and date delta `{yyyymmdd - 1d}`, the current datetime would be extracted from `env["BIZDATE"]`, follows the design of PAI, the `BIZDATE` is a Datetime string of format `%Y%m%d`.
