### ISSUE TITLE
Support for command line

### ISSUE THREAD

**Issue by BlackPoint-CX** [sql-machine-learning/pysqlflow#87]
Description:
SQLFlow should support command line like 'hive -e <quoted-query-string>' or 'hive -f <filename>'. 
It could help developer or other users to schedule the running of SQLFlow task.

**Comment by tonyyang-svail** [comment]
Actually, there is already a command line `sqlflow`. If you type `sqlflow -h` in our docker image, you should be able to see the following.
```
sqlflow -h
usage: sqlflow [-h] [--url URL] [--ca_crt CA_CRT] sql [sql ...]

positional arguments:
  sql              sql

optional arguments:
  -h, --help       show this help message and exit
  --url URL        server url
  --ca_crt CA_CRT  Path to CA certificates of SQLFlow client.
```

However, I just realize there is a bug in our command line, so I am filing a PR to fix it.

The updated command line should be available in the release.

@Yancey1989 Let's aim to release it together with https://github.com/sql-machine-learning/sqlflow/pull/966 next week.
