### ISSUE TITLE
make release still succeed to publish to pypi when the command fails

### ISSUE THREAD

**Issue by typhoonzero** [sql-machine-learning/pysqlflow#91]
The log of running make release:

```
# Tag it
git tag v0.7.0
git push --tags
总共 0 （差异 0），复用 0 （差异 0）
To https://github.com/sql-machine-learning/pysqlflow.git
 * [new tag]         v0.7.0 -> v0.7.0
# Bump version for development
git checkout develop
切换到分支 'develop'
您的分支领先 'origin/develop' 共 1 个提交。
  （使用 "git push" 来发布您的本地提交）
sed -i '' -E "s/[0-9]+, [0-9]+, [0-9]+/0, 8, 0, 'dev'/" sqlflow/_version.py
git commit -a -m "start 0.8.0"
[develop 46f42d0] start 0.8.0
 1 file changed, 1 insertion(+), 1 deletion(-)
git push origin develop
枚举对象: 7, 完成.
对象计数中: 100% (7/7), 完成.
使用 8 个线程进行压缩
压缩对象中: 100% (4/4), 完成.
写入对象中: 100% (4/4), 394 字节 | 394.00 KiB/s, 完成.
总共 4 （差异 2），复用 0 （差异 0）
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.
To https://github.com/sql-machine-learning/pysqlflow.git
 ! [remote rejected] develop -> develop (protected branch hook declined)
error: 推送一些引用到 'https://github.com/sql-machine-learning/pysqlflow.git' 失败
```

By the way seems `make release` only works on mac, not in docker ubuntu image.

**Comment by tonyyang-svail** [comment]
This is what happened in your `make release`, we

1. Git push the master.
1. Git push the release tag.
1. Update the develop branch.

The first and second steps succeeded, while the third step failed because `develop` branch can only be pushed by repo admin.

I will do the following to fix the current limbo.

1. Delete the master branch, since we are not using the master branch anyway.
1. Release `v0.7.1`.
1. Update the develop branch.

**Comment by tonyyang-svail** [comment]
To prevent situations like this happening again. I also update the Makefile by putting `git push --tag` after `git push origin develop`.

**Comment by tonyyang-svail** [comment]
Done.

![Screen Shot 2019-10-18 at 1 06 33 PM](https://user-images.githubusercontent.com/29932814/67124793-25a6d100-f1a8-11e9-8092-dc185a1c0de7.png)
